### PR TITLE
Better interop with NodeJS-native ES Modules

### PR DESCRIPTION
**Pull request by sjockers**
**Motivation:**

Make package work with modern NodeJS (native ES Modules) 

**Changes:**

- Set `type` to `module` so that NodeJS understands that `.js` files are written in ES Module syntax
- Rename files that use CommonJS syntax to `.cjs` to trigger proper handling in NodeJS (specifically used in tests & exports)
- Add file extensions to imports for better compatibility with ES Modules
- Provide [dual exports](https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_dual_commonjs_es_module_packages) so that the package can be both imported and required in NodeJS
- Explicitly export`essentials` and `selection` builds (ES Modules only — this mimics the previous behavior) 
- Upgrade unit tests (`tape` & `jsdom`) to play nice with the new ES Module setup

### CODE REVIEW

**Comment by 1wheel** [comment]
Awesome! I was just trying to figure out how to do this last night, using v3 of d3-transition as a starting point. Questions:

- Do we need the `sideEffects` or `peerDependencies` properties like [d3-transition](https://github.com/d3/d3-transition/blob/main/package.json) has? d3-transition also imports a range of packages (`"d3-color": "1 - 3",`)
- Since D3 is [dropping](https://github.com/d3/d3/issues/3501) CommonJS exports does it make sense to bother with duel exports instead of just doing a major version bump? 
- If we're doing a major version bump, should we also switch over to d3v7 once their ESM conversion is finished? I think only a couple of small changes to `nestBy`, `attachTooltip` and `loadData` would be needed along with a refresh of the documentation. cc @gka

**Comment by sjockers** [comment]
Thanks so much for your feedback!

> Do we need the sideEffects or peerDependencies properties like d3-transition has? d3-transition also imports a range of packages ("d3-color": "1 - 3",)

I don’t think it’s absolutely necessary as long as we keep the D3 packages as regular dependencies, but it would probably improve support for tree shaking etc. However, I don't know enough of the specifics of D3 & jetpack to decide what ranges to pick for `peerDependencies` and what should be a `sideEffect`. If you have ideas about that, let me know.
 
> Since D3 is dropping CommonJS exports does it make sense to bother with duel exports instead of just doing a major version bump?

Right now I'm mostly trying to get the current version to play nice with ES Modules in order to fix some tooling issues we have Datawrapper. So for now I’d be happy with a new minor version that provides the same exports as before, but in a way that can be properly handled by Node. @gka, what do you think?

**Comment by 1wheel** [comment]
D3's API hasn't changed too much since being split into modules and jetpack doesn't hit too many edge cases; I think `1 - 3` should work just fine.

I'm not sure how modern javascript works, but I think peer dependencies of `2-3` for `d3-transition` and `d3-selection` might fix #68.

Merging this as is to fix the tooling issue also works; the major version bump can wait till d3's.

**Review by gka — APPROVED** [review]

**Comment by sjockers** [comment]
@1wheel Hey Adam, thanks again for your feedback. I've added `peerDependencies` and `sideEffects` per your suggestion. I've also discussed this with @gka and we decided to stick with v1 dependencies for now to keep backwards compatibility. We haven't merged this into master yet because it needs more testing, but we're working on a new release here: https://github.com/gka/d3-jetpack/pull/76

**Pull request merged**
